#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_home:
    path: dstoi/
    controller: App\Controller\HomeController::index
    methods: GET
auth_signup:
    path: dstoi/SignUp
    controller: App\Controller\AuthorizationController::getSignUp
    methods: GET
auth_signup_post:
    path: dstoi/SignUp
    controller: App\Controller\AuthorizationController::postSignUp
    methods: POST
auth_signin:
    path: dstoi/SignIn
    controller: App\Controller\AuthorizationController::getSignIn
    methods: GET
auth_signin_post:
    path: dstoi/SignIn
    controller: App\Controller\AuthorizationController::postSignIn
    methods: POST
auth_logout:
    path: dstoi/LogOut
    controller: App\Controller\AuthorizationController::logOut
    methods: GET
usr_profile:
    path: dstoi/Profile
    controller: App\Controller\ProfileController::index
    methods: GET
app_content:
    path: dstoi/append
    controller: App\Controller\ContentController:index
    methods: GET
app_content_post:
    path: dstoi/append
    controller: App\Controller\ContentController:postContent
    methods: POST 
app_page_content:
    path: dstoi/{id}
    controller: App\Controller\ViewContentController:page
    methods: GET 
